import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';
import { AuthService } from '../_services/auth.service';
import { AlertifyService } from '../_services/alertify.service';

// this folder was created by user, and this ts file was generated by
// cd DatingApp-SPA/src/app/_guards/ then ng g guard auth --spec=false

@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanActivate {

constructor(private authService: AuthService,
private router: Router, private alertify: AlertifyService) {}

  canActivate(): boolean {

    if (this.authService.loggedIn()) {
      return true;
    }


   this.alertify.error('You shall not pass !!');
   this.router.navigate(['/home']);
   return false;

  }
}
